---

- name: standard
  hosts: all
  become: true
  gather_facts: true

  vars_prompt:
    - name: user
      prompt: username
      private: no
      default: "{{lookup('ansible.builtin.env', 'USER') | default('nobody', True)}}"

  roles:
    - role: vbox
      tags: vbox
      when:
        - ansible_facts['virtualization_role'] == "guest"
        - ansible_facts['virtualization_type'] == "virtualbox"
        - vagrant | default(false) | bool
    - role: core
      tags: core
    - role: base
      tags: base
    - role: user
      tags: user

  pre_tasks:
    - name: check requirements
      block:
        - name: check ansible version
          ansible.builtin.assert:
            that: ansible_version.full is version('2.10', '>=')
            fail_msg: "unsupported ansible version: {{ansible_version}}"

        - name: check supported os
          ansible.builtin.assert:
            that:
              - ansible_facts['distribution'] == "Ubuntu"
              - ansible_facts['distribution_major_version'] is version('22', '==')
            fail_msg: "unsupported os: {{ansible_facts['distribution']}} {{ansible_facts['distribution_version']}}"

        - name: check architecture
          ansible.builtin.assert:
            that: ansible_facts['architecture'] == "x86_64"
            fail_msg: "unsupported architecture: {{ansible_facts['architecture']}}"

        - name: update apt cache
          ansible.builtin.apt:
            update_cache: true
          changed_when: false
      tags:
        - always

