---

- name: add additional apt repos
  vars:
    keyring: /usr/share/keyrings
  block:
    - name: add repo key
      get_url:
        url: '{{item.key.url}}'
        dest: '{{keyring}}/{{item.key.dest}}'
      loop: '{{repos}}'
      loop_control:
        label: '{{item.name}}'

    - name: add repo
      apt_repository:
        repo: deb [arch=amd64 signed-by={{keyring}}/{{item.key.dest}}] {{item.repo}}
        state: present
        filename: '{{item.name}}'
      loop: '{{repos}}'
      loop_control:
        label: '{{item.name}}'

- name: allow wireshark to run non-root # must be set prior to installing package
  debconf:
    name: wireshark-common
    question: wireshark-common/install-setuid
    value: 'true'
    vtype: select

- name: install core dev tools
  package:
    state: present
    name:
      - ansible
      - build-essential
      - cmake
      - code
      - cppcheck
      - curl
      - docker.io
      - docker-buildx
      - docker-compose-v2
      - dos2unix
      - gdb-multiarch
      - git
      - git-completion
      - git-gui
      - git-lfs
      - gitk
      - lcov
      - make
      #- nemiver
      - netcat
      - rlwrap
      - socat
      - tcpdump
      - vagrant
      - valgrind
      - wget

- name: install user packages
  package:
    state: present
    name:
      - autojump
      - brave-browser # google-chrome-stable
      - celluloid # parole
      - deja-dup # gtk3
      - font-manager
      - fzf
      - ghex
      - gimp # no install recommends?
      - gnome-disk-utility # gtk3 (gparted)
      - gnome-firmware # gtk3
      - gpicview # ristretto, eom
      - gtkterm
      - htop
      - keepassxc
      - libreoffice-calc
      - libreoffice-gtk3
      - libreoffice-help-en-us
      - libreoffice-impress
      - libreoffice-style-breeze
      - libreoffice-writer
      - libsdl-ttf2.0-0 # vbox
      - mate-calc # galculator
      - meld
      - mousepad # pluma
      - ncdu # baobab (gtk3), ducs
      - neofetch
      - pdfgrep
      - pipx
      - python3
      - python3-pip
      - python3-psutil # ansible dconf module
      - python3-setuptools
      - python3-venv
      #- qt5-default
      #- redshift-gtk
      #- remmina
      #- remmina-plugin-rdp
      #- audacious, lxmusic, lollypop, cmus, moc
      - tmux
      - tree
      - usb-creator-gtk
      - vim
      - virtualbox-7.0
      - wireshark
      - xterm
      - zathura # atril, evince

- name: install vscode extensions
  become_user: '{{user}}'
  command: 'code --install-extension {{item}}'
  register: install_vscode_extension
  args:
    creates: '~/.vscode/extensions/{{item}}-*'
  loop:
    - ms-vscode.cpptools
    - ms-vscode.makefile-tools
    - ms-vscode.cmake-tools
    - ms-vscode-remote.remote-containers
    - ms-vscode.hexeditor
    - ms-python.python
    - ms-python.debugpy
    - ms-azuretools.vscode-docker
    - rust-lang.rust-analyzer
    - redhat.ansible
    - vscode-icons-team.vscode-icons

- name: install latest rust
  become_user: '{{user}}'
  shell:
    cmd: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    creates: ~/.cargo/bin/rustc

- name: add user groups
  user:
    name: '{{user}}'
    append: true
    groups:
      - dialout
      - users
      - wireshark
      - docker

- name: user config
  become_user: '{{user}}'
  block:
    - name: remove xdg user dirs
      file:
          path: '~/{{item}}'
          state: absent
      loop:
        - Templates
        - Public
      register: xdg_user_dirs

    - name: update xdg user dirs
      command: xdg-user-dirs-update
      when: xdg_user_dirs.changed

    - name: config bashrc
      blockinfile:
        path: ~/.bashrc
        block: "{{lookup('file', 'files/home/bashrc')}}"
        insertafter: EOF

