---

- name: add apt repos
  block:
    - name: add virtualbox key
      apt_key:
        url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
        state: present
    - name: add virtualbox repo
      apt_repository:
        repo: deb [arch=amd64] http://download.virtualbox.org/virtualbox/debian focal contrib
        state: present
        filename: virtualbox

    - name: add microsoft key
      apt_key:
        url: https://packages.microsoft.com/keys/microsoft.asc
        state: present
    - name: add vscode repo
      apt_repository:
        repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
        state: present
        filename: vscode

    - name: add google key
      apt_key:
        url: https://dl.google.com/linux/linux_signing_key.pub
        state: present
    - name: add google chrome repo
      apt_repository:
        repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb stable main
        state: present
        filename: google-chrome

    - name: add brave browser key
      apt_key:
        url: https://brave-browser-apt-release.s3.brave.com/brave-core.asc
        state: present
    - name: add brave browser repo
      apt_repository:
        repo: deb [arch=amd64] http://brave-browser-apt-release.s3.brave.com stable main
        state: present
        filename: brave-browser-release

- name: allow wireshark to run non-root # must be set prior to installing package
  debconf:
    name: wireshark-common
    question: wireshark-common/install-setuid
    value: 'true'
    vtype: select

- name: install user packages
  package:
    state: present
    update_cache: yes
    name:
      - brave-browser # google-chrome-stable
      - celluloid # parole
      - cmake
      - code
      - deja-dup # gtk3
      - docker.io
      - font-manager
      - gdb-multiarch
      - ghex
      - gimp # no install recommends?
      - git
      - git-gui
      - git-lfs
      - gitk
      #- gnome-disk-utility # gtk3 (gparted)
      #- gnome-firmware # gtk3
      - gtkterm
      - keepassxc
      - libreoffice-calc
      - libreoffice-gtk3
      - libreoffice-help-en-us
      - libreoffice-impress
      - libreoffice-style-breeze
      - libreoffice-writer
      - libsdl-ttf2.0-0 # vbox
      - mate-calc # galculator
      - meld
      #- mousepad # pluma
      - ncdu # baobab (gtk3), ducs
      #- nemiver
      - neofetch
      - pdfgrep
      #- qt5-default
      #- redshift-gtk
      #- remmina
      #- remmina-plugin-rdp
      #- audacious, lxmusic, lollypop, cmus, moc
      - gpicview # ristretto, eom
      - sqlite3
      - tmux
      - usb-creator-gtk
      - valgrind
      - vim
      - virtualbox-6.1
      - wireshark
      - zathura # atril, evince

- name: install vscode extensions
  become_user: '{{user}}'
  command: 'code --install-extension {{item}}'
  register: install_vscode_extension
  args:
    creates: '~/.vscode/extensions/{{item}}-*'
  loop:
    - ms-vscode.cpptools
    - ms-python.python
    - ms-azuretools.vscode-docker
    - redhat.ansible
    - rust-lang.rust

- name: install latest rust
  become_user: '{{user}}'
  shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  args:
    creates: ~/.cargo/bin/rustc
    warn: false

- name: add user groups
  user:
    name: '{{user}}'
    append: yes
    groups: [dialout, users, wireshark, docker]

- name: user config
  become_user: '{{user}}'
  block:
    - name: remove xdg user dirs
      file:
          path: '~/{{item}}'
          state: absent
      loop:
        - Templates
        - Public
      register: xdg_user_dirs

    - name: update xdg user dirs
      command: xdg-user-dirs-update
      when: xdg_user_dirs.changed

    - name: config bashrc
      blockinfile:
        path: ~/.bashrc
        block: "{{lookup('file', 'files/home/bashrc')}}"
        insertafter: EOF

    - name: config git
      copy:
        src: 'files/home/{{item}}'
        dest: '~/.{{item}}'
        mode: 0644
      loop:
        - gitconfig
        - gitignore

    - name: config vimrc
      copy:
        src: files/home/vimrc
        dest: ~/.vimrc
        mode: 0644
      register: vimrc

    - name: create vim user dir
      file:
          path: '~/.vim'
          state: directory
          mode: 0755

    - name: clone vim plug
      git:
        clone: yes
        repo: https://github.com/junegunn/vim-plug.git
        dest: ~/.vim/vim-plug/autoload

    - name: install vim plugins
      command: vim -E -s -u ~/.vimrc -c PlugInstall -c qa
      when: vimrc.changed
      register: install_vim_plugins
      failed_when: install_vim_plugins.rc != 0

    - name: config tmux
      copy:
        src: files/home/tmux.conf
        dest: ~/.tmux.conf
        mode: 0644

    - name: clone tmux themepack
      git:
        clone: yes
        version: 1.1.0
        repo: https://github.com/jimeh/tmux-themepack.git
        dest: ~/.tmux/tmux-themepack

    - name: config conky
      copy:
        src: files/home/conkyrc
        dest: ~/.conkyrc
        mode: 0644

