---

- name: install updates
  ansible.builtin.apt:
    upgrade: dist
    autoremove: true

- name: install core system packages
  ansible.builtin.apt:
    state: present
    name:
      - acl
      - apparmor
      - apparmor-utils
      - bzip2
      - cifs-utils
      - cpufrequtils
      - cryptsetup
      - cryptsetup-initramfs
      - dkms
      - ethtool
      - fdisk
      - fwupd
      - fwupd-signed
      - gdisk
      - git
      - htop
      - hwdata
      - jq
      - laptop-detect
      - libfuse2
      - lvm2
      - net-tools
      - network-manager
      - p7zip-full
      - python-is-python3
      - python3-pip
      - python3-setuptools
      - python3-venv
      - python3-wheel
      - shim-signed
      - sysstat
      - tmux
      - ubuntu-standard
      - ufw
      - unzip
      - vim
      - xz-utils
      - zerofree
      - zip

- name: install ssh server
  block:
    - name: install ssh server
      ansible.builtin.apt:
        state: present
        name:
          - openssh-server

    - name: enable sshd services
      ansible.builtin.systemd_service:
        name: sshd
        enabled: true
        state: started
  when: sshd | bool

- name: install core system packages (no recommends)
  ansible.builtin.apt:
    state: present
    install_recommends: false
    name:
      - inxi
      - neofetch
      - pipx

- name: add snap support
  ansible.builtin.apt:
    state: present
    name:
      - snap
      - snapd
  when: repos.snap | bool

- name: install plymouth boot splash
  ansible.builtin.apt:
    state: present
    name:
      - plymouth
      - plymouth-theme-ubuntu-text
      - plymouth-theme-spinner
      - plymouth-x11
  notify: update initramfs

