---

- name: install updates
  ansible.builtin.apt:
    upgrade: dist
    autoremove: true

- name: install core system packages
  ansible.builtin.apt:
    state: present
    name: "{{pkgs.common + pkgs[ansible_facts['distribution_version']]}}"

- name: install ssh server
  block:
    - name: install ssh server
      ansible.builtin.apt:
        state: present
        name:
          - openssh-server

    - name: enable sshd services
      ansible.builtin.systemd_service:
        name: ssh
        enabled: true
        state: started
  when: sshd | bool

- name: install core system packages (no recommends)
  ansible.builtin.apt:
    state: present
    install_recommends: false
    name:
      - "{{'neofetch' if ansible_facts['distribution_major_version'] is version('26', '<') else 'fastfetch'}}"
      - inxi
      - pipx

- name: add snap support
  ansible.builtin.apt:
    state: present
    name:
      - snap
      - snapd
  when: repos.snap | bool

- name: install plymouth boot splash
  ansible.builtin.apt:
    state: present
    name:
      - plymouth
      - plymouth-theme-ubuntu-text
      - plymouth-theme-spinner
      - plymouth-x11
  notify: update initramfs

