---

- name: cleanup server install
  ansible.builtin.import_tasks: cleanup.yml

- name: install core system
  ansible.builtin.import_tasks: core.yml

- name: setup core system
  ansible.builtin.import_tasks: setup.yml

