---

- name: install login manager
  ansible.builtin.apt:
    state: present
    name:
      - lightdm
      - lightdm-settings
      - light-locker
      - light-locker-settings
      - slick-greeter

- name: install awesomewm
  ansible.builtin.import_tasks: awesome.yml
  tags: awesomewm
  notify: restart lightdm

- name: install qtile
  ansible.builtin.import_tasks: qtile.yml
  tags: qtile
  notify: restart lightdm

- name: install core software
  ansible.builtin.apt:
    state: present
    name:
      - arandr
      - fonts-ubuntu
      - kitty
      #- firefox # note: snap
      - lxappearance
      - lxpolkit
      - maim # scrot, flameshot, gnome-screenshot
      - network-manager-gnome # note: depends on gnome shell unless policykit auth agent (lxpolkit) and notification daemon installed (awesome, dunst)
      - nitrogen
      - pavucontrol
      - pasystray
      - pcmanfm
      - picom
      - playerctl
      - ranger
      - rofi
      - rxvt-unicode
      - sxiv
      - vim
      - xarchiver # engrampa

- name: install themes
  ansible.builtin.apt:
    state: present
    name:
      - arc-theme
      - gtk2-engines
      - papirus-icon-theme
      - qt5ct
      - qt5-gtk-platformtheme
      - qt5-gtk2-platformtheme
      - qt6-gtk-platformtheme
      - ubuntu-wallpapers

#- name: install themes (no recommends)
#  ansible.builtin.apt:
#    state: present
#    install_recommends: false
#    name:
#      - qt5-style-kvantum
#      - qt5-style-kvantum-themes

