---

- name: install login manager
  ansible.builtin.apt:
    state: present
    name:
      - lightdm
      - lightdm-settings
      - light-locker
      - light-locker-settings
      - slick-greeter

- name: install awesomewm
  ansible.builtin.import_tasks: awesome.yml
  tags: awesomewm
  notify: restart lightdm

- name: install qtile
  ansible.builtin.import_tasks: qtile.yml
  tags: qtile
  notify: restart lightdm

- name: install core software
  ansible.builtin.apt:
    state: present
    name:
      - arandr
      - picom # compton
      #- firefox # note: snap
      - libnotify-bin # note: depends on gnome shell unless notification daemon installed (awesome, dunst)
      - lxappearance
      - lxpolkit
      - maim # scrot, flameshot, gnome-screenshot
      - network-manager-gnome # note: depends on gnome shell unless policykit auth agent (lxpolkit) and notification daemon installed (awesome, dunst)
      - nitrogen
      - pasystray
      - pcmanfm
      - playerctl
      - ranger
      - rofi
      - rxvt-unicode
      - sxiv
      - vim
      #- update-manager # note: depends on gnome shell unless policykit auth agent installed (lxpolkit) (also requires session manager)
      - xarchiver # engrampa

- name: install core software (no recommends)
  ansible.builtin.apt:
    state: present
    install_recommends: false
    name:
      - kitty

- name: install fonts
  ansible.builtin.apt:
    state: present
    name:
      - fonts-fork-awesome
      - fonts-freefont-ttf 
      - fonts-firacode
      - fonts-ubuntu
      - fonts-ubuntu-console
      - powerline

- name: install themes
  ansible.builtin.apt:
    state: present
    name:
      - arc-theme
      - dmz-cursor-theme
      - gtk2-engines
      - papirus-icon-theme
      - qt5ct
      - qt5-gtk-platformtheme
      - qt5-gtk2-platformtheme
      - qt6-gtk-platformtheme
      - ubuntu-wallpapers

- name: install themes (no recommends)
  ansible.builtin.apt:
    state: present
    install_recommends: false
    name:
      - qt5-style-kvantum
      - qt5-style-kvantum-themes

- name: configure gtk theme
  become_user: '{{user}}'
  block:
    - name: configure gtk2 theme
      ansible.builtin.copy:
        src: files/home/gtkrc-2.0
        dest: ~/.gtkrc-2.0

    - name: configure gtk3 theme
      ansible.builtin.copy:
        src: files/home/config/gtk-3.0
        dest: ~/.config

