---

- name: install qtile
  ansible.builtin.pip:
    state: present
    name: qtile
    virtualenv: /opt/qtile
    virtualenv_command: python3 -m venv

- name: install qtile xsession launcher
  ansible.builtin.copy:
    src: files/usr/share/xsessions/qtile.desktop
    dest: /usr/share/xsessions
    mode: '0644'

