---

apt_repos:
  - name: brave-browser
    url: https://brave-browser-apt-release.s3.brave.com
    suite: stable
    component: main
    key: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg

  - name: google-chrome
    url: https://dl.google.com/linux/chrome/deb
    suite: stable
    component: main
    key: https://dl.google.com/linux/linux_signing_key.pub

  - name: hashicorp
    url: https://apt.releases.hashicorp.com
    suite: "{{ansible_facts['distribution_release']}}"
    component: main
    key: https://apt.releases.hashicorp.com/gpg

  - name: mozilla
    url: https://packages.mozilla.org/apt
    suite: mozilla
    component: main
    key: https://packages.mozilla.org/apt/repo-signing-key.gpg

  - name: virtualbox
    url: https://download.virtualbox.org/virtualbox/debian
    suite: "{{ansible_facts['distribution_release']}}"
    component: contrib
    key: https://www.virtualbox.org/download/oracle_vbox_2016.asc

  - name: vscode
    url: https://packages.microsoft.com/repos/code
    suite: stable
    component: main
    key: https://packages.microsoft.com/keys/microsoft.asc

pkgs_desktop:
  - '{{pkg_select.archiver | default()}}'
  - '{{pkg_select.browser | default()}}'
  - '{{pkg_select.editor | default()}}'
  - '{{pkg_select.file_manager | default()}}'
  - '{{pkg_select.launcher | default()}}'
  - '{{pkg_select.terminal | default()}}'
  - arandr
  - blueman
  - fonts-ubuntu
  - lxappearance
  - lxpolkit
  - network-manager-gnome # note: requires policykit agent (lxpolkit) and notification daemon (awesome, dunst) or gnome-shell installed
  - "{{'nitrogen' if ansible_facts['distribution_major_version'] is version('26', '<') else 'feh'}}"
  - pavucontrol
  - pasystray
  - picom

