---

apt_repos:
  - name: brave-browser
    repo: https://brave-browser-apt-release.s3.brave.com stable main
    key:
      url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
      dest: brave-browser-archive-keyring.gpg

  - name: google-chrome
    repo: https://dl.google.com/linux/chrome/deb stable main
    key:
      url: https://dl.google.com/linux/linux_signing_key.pub
      dest: google.asc

  - name: hashicorp
    repo: https://apt.releases.hashicorp.com {{ansible_facts['distribution_release']}} main
    key:
      url: https://apt.releases.hashicorp.com/gpg
      dest: hashicorp-archive-keyring.asc

  - name: mozilla
    repo: https://packages.mozilla.org/apt mozilla main
    key:
      url: https://packages.mozilla.org/apt/repo-signing-key.gpg
      dest: mozilla.asc

  - name: virtualbox
    repo: https://download.virtualbox.org/virtualbox/debian {{ansible_facts['distribution_release']}} contrib
    key:
      url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
      dest: oracle_vbox_2016.asc

  - name: vscode
    repo: https://packages.microsoft.com/repos/code stable main
    key:
      url: https://packages.microsoft.com/keys/microsoft.asc
      dest: microsoft.asc

pkgs_desktop:
  - '{{pkgs.archiver | default()}}'
  - '{{pkgs.browser | default()}}'
  - '{{pkgs.editor | default()}}'
  - '{{pkgs.file_manager | default()}}'
  - '{{pkgs.launcher | default()}}'
  - '{{pkgs.terminal | default()}}'
  - arandr
  - blueman
  - fonts-ubuntu
  - lxappearance
  - lxpolkit
  - network-manager-gnome # note: requires policykit agent (lxpolkit) and notification daemon (awesome, dunst) or gnome-shell installed
  - nitrogen
  - pavucontrol
  - pasystray
  - picom

