---

pkg_enable:
  devtools: true
  docker: true
  lazydocker: true
  lazygit: true
  libreoffice: false
  neovim: true
  rust: false
  virtualbox: true
  vscode: false
  wireshark: false

pkg_select:
  audio: cmus # audacious, cmus, lollypop, lxmusic, moc, rhythmbox
  video: celluloid # celluloid, mpv, parole
  image: # eom, gimp, gpicview, ristretto, sxiv
    - gimp
    - gpicview
    - sxiv
  editor: # gedit, mousepad, pluma, vim
    - mousepad
    - vim
  office: zathura # atril, evince, libreoffice, zathura
  backup: deja-dup # borgbackup, deja-dup, timeshift
  calc: mate-calc # galculator, mate-calc
  utils:
    - font-manager
    - ghex
    - gnome-disk-utility # gparted
    - gpick
    - gtkterm
    - keepassxc
    - maim # flameshot, maim, scrot
    - meld
    - ncdu # baobab, ducs, dcdu
    - usb-creator-gtk

# ref: https://marketplace.visualstudio.com/vscode
vscode_extensions:
  - ms-vscode.cpptools
  - ms-vscode.makefile-tools
  - ms-vscode.cmake-tools
  - ms-vscode-remote.remote-containers
  - ms-vscode.hexeditor
  - ms-python.python
  - ms-azuretools.vscode-docker
  - rust-lang.rust-analyzer
  - redhat.ansible
  - vscode-icons-team.vscode-icons

nerd_fonts:
  - name: FiraCode
    pkg: FiraCode
  #- name: JetBrainsMono
  #  pkg: JetBrainsMono
  #- name: SauceCodePro
  #  pkg: SourceCodePro

dotfiles:
  repo: https://github.com/dgeletko/dotfiles.git
  dest: /home/{{user}}/src/dotfiles
  pkgs:
    - awesome
    - kitty
    - nvim
    - picom
    - qtile
    - ranger
    - rofi
    - tmux
    - vim
    - Xresources

