---

apps:
  docker: true
  libreoffice: false
  rust: false
  virtualbox: true
  vscode: false
  wireshark: false

# ref: https://marketplace.visualstudio.com/vscode
vscode_extensions:
  - ms-vscode.cpptools
  - ms-vscode.makefile-tools
  - ms-vscode.cmake-tools
  - ms-vscode-remote.remote-containers
  - ms-vscode.hexeditor
  - ms-python.python
  - ms-python.debugpy
  - ms-azuretools.vscode-docker
  - rust-lang.rust-analyzer
  - redhat.ansible
  - vscode-icons-team.vscode-icons

nerd_fonts:
  - name: FiraCode
    pkg: FiraCode
  #- name: JetBrainsMono
  #  pkg: JetBrainsMono
  #- name: SauceCodePro
  #  pkg: SourceCodePro

dotfiles:
  repo: https://github.com/dgeletko/dotfiles.git
  dest: /home/{{user}}/src/dotfiles
  pkgs:
    - awesome
    - kitty
    - nvim
    - picom
    - qtile
    - ranger
    - rofi
    - tmux
    - vim
    - Xresources

